In [2]:
#データを生成
import numpy as np
m = 100
X = 6 * np.random.rand(m, 1) - 3
y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)

In [3]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly_features.fit_transform(X) # φによって、データxを(x,x^{2})に変換

In [4]:
X[0] #変換前のデータ

array([1.32268224])

In [5]:
X_poly[0] #変換後のデータ

array([1.32268224, 1.7494883 ])

In [7]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression() #線形回帰モデルを選択
lin_reg.fit(X_poly, y) #最適解を求める

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
lin_reg.coef_ #wの最適解

array([[0.94041935, 0.49876073]])

In [9]:
lin_reg.intercept_ #bの最適解

array([1.98435621])