In [2]:
#データを取得
from sklearn import datasets
import numpy as np
iris = datasets.load_iris()
X = iris["data"][:, 3:]  # petal width
y = (iris["target"] == 2).astype(np.int)  # 1 if Iris virginica, else 0

In [8]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver="lbfgs") #ロジスティック回帰モデルを選択
log_reg.fit(X, y) #最適解を求める

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [9]:
log_reg.coef_ #wの最適解

array([[4.3330846]])

In [10]:
log_reg.intercept_ #bの最適解

array([-7.1947083])

In [11]:
log_reg.predict([[1.7], [1.5]]) #値を予測

array([1, 0])