In [4]:
#データを生成
import numpy as np
X=np.random.rand(10, 4)
print(X)

[[0.57474458 0.16751176 0.35264397 0.4309027 ]
 [0.18800478 0.60807862 0.91871515 0.0232249 ]
 [0.6039462  0.9651043  0.57734071 0.51948878]
 [0.64712874 0.17814374 0.14483057 0.03151927]
 [0.62575414 0.87310484 0.64126612 0.54786158]
 [0.49916027 0.259644   0.97128355 0.46407301]
 [0.22934534 0.38941088 0.42845559 0.1687856 ]
 [0.46389123 0.60854082 0.06718675 0.73438477]
 [0.80296074 0.39762404 0.02174463 0.33213051]
 [0.243695   0.38014572 0.63414172 0.57011153]]


In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2) #２次元空間へ射影する
pca.fit(X) #Xの平均を0にしてから、Wを構成する

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [7]:
pca.components_ #主成分を表示

array([[-0.34658604,  0.29375681,  0.89071272, -0.01469369],
       [ 0.23731118,  0.75216648, -0.14587216,  0.59720207]])

In [9]:
X2d = pca.fit_transform(X) #Xを射影する
print(X2d)

[[-0.23308638 -0.16946345]
 [ 0.54056884 -0.25590155]
 [ 0.18992958  0.45751559]
 [-0.43428412 -0.35248728]
 [ 0.21186806  0.4011113 ]
 [ 0.37071732 -0.18853457]
 [ 0.0231864  -0.25212114]
 [-0.32383051  0.35883747]
 [-0.53787078  0.04705959]
 [ 0.1928016  -0.04601596]]
