In [26]:
import numpy as np

In [27]:
# W,bを設定
W = np.random.randn(2,3)
b = np.random.randn(1,2)
W,b

(array([[-0.3275861 ,  0.35679815, -0.93635564],
        [-0.3966737 ,  2.45340843,  0.80369067]]),
 array([[ 0.73728049, -0.99336306]]))

In [28]:
# fを設定
def f(x):
  return 1/1+np.exp(-x)

In [29]:
# FNを設定
def FN(W,b,f,x):
  x = x.T
  Z = np.dot(W,x)+b
  return f(Z)

In [31]:
#出力
x = np.array([0.1,0.2,0.3])
FN(W,b,f,x)


array([[1.60958626, 2.35153575]])