In [18]:
import numpy as np

In [19]:
# W_1,b_1を設定
W_1 = np.random.randn(2,3)
b_1 = np.random.randn(1,2)
W_1,b_1

(array([[-0.85226586, -0.74838968, -0.47477658],
        [ 0.9893178 , -0.17452691,  0.08049864]]),
 array([[-0.1930833 , -1.26376165]]))

In [20]:
# f_1を設定
def f_1(x):
  return 1/1+np.exp(-x)

In [21]:
# FNを設定
def FN(W,b,f,x):
  x = x.T
  Z = np.dot(W,x)+b
  return f(Z)

In [28]:
# W_2,b_2を設定
W_2= np.random.randn(1,2)
b_2= np.random.randn()
W_2,b_2

(array([[-0.79262461, -1.11520968]]), 1.4734070700523327)

In [30]:
#f_2を設定
def f_2(x):
  return x

In [31]:
#出力
x = np.array([0.1,0.2,0.3])
x = FN(W_1,b_1,f_1,x)
FN(W_2,b_2,f_2,x)

array([[-5.44991305]])